# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
"""Tests for the Kiro installer's legacy-cleanup behavior.

v0.5.x removed the pre-registered composer agent (composers are self-spawned
via the persona's spawn template). The installer must remove the legacy
generated ``~/.kiro/agents/sdpm-composer.json`` — but ONLY when it matches
the known generated form for this checkout; user-edited files or files
generated by another checkout are left in place with a warning.
"""

import importlib.util
import json
from pathlib import Path

import pytest

_INSTALL_PY = Path(__file__).resolve().parent.parent / "clients" / "kiro" / "install.py"
_spec = importlib.util.spec_from_file_location("kiro_install", _INSTALL_PY)
kiro_install = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_spec and kiro_install)


def _generated_config(repo_root: Path) -> dict:
    """The exact structure the old installer template rendered."""
    return {
        "name": "sdpm-composer",
        "description": "sdpm slide composer (dispatched by the sdpm-vibe skill). "
        "Composes assigned slides from approved specs via the sdpm MCP server. "
        "No user interaction.",
        "prompt": f"file://{repo_root}/personas/composer.md",
        "mcpServers": {
            "sdpm": {
                "command": "uv",
                "args": ["run", "--directory", f"{repo_root}/servers/local", "python", "server.py"],
                "timeout": 120000,
            }
        },
        "tools": ["read", "glob", "grep", "@sdpm"],
        "allowedTools": ["read", "glob", "grep", "@sdpm"],
        "useLegacyMcpJson": False,
    }


@pytest.fixture
def agents_dir(tmp_path):
    d = tmp_path / "agents"
    d.mkdir()
    return d


def _write_legacy(agents_dir: Path, config) -> Path:
    p = agents_dir / "sdpm-composer.json"
    p.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
    return p


REPO_ROOT = kiro_install.REPO_ROOT


class TestCleanupLegacyComposerAgent:
    def test_removes_known_generated_form(self, agents_dir):
        p = _write_legacy(agents_dir, _generated_config(REPO_ROOT))
        kiro_install.cleanup_legacy_composer_agent(agents_dir, REPO_ROOT)
        assert not p.exists()

    def test_formatting_differences_do_not_block_cleanup(self, agents_dir):
        # Old installer wrote the rendered template verbatim — indentation
        # and key order may differ across versions. Structure decides.
        p = agents_dir / "sdpm-composer.json"
        p.write_text(json.dumps(_generated_config(REPO_ROOT)), encoding="utf-8")
        kiro_install.cleanup_legacy_composer_agent(agents_dir, REPO_ROOT)
        assert not p.exists()

    def test_keeps_user_edited_tools(self, agents_dir):
        cfg = _generated_config(REPO_ROOT)
        cfg["tools"] = ["read", "glob", "grep", "@sdpm", "shell"]  # user widened
        p = _write_legacy(agents_dir, cfg)
        kiro_install.cleanup_legacy_composer_agent(agents_dir, REPO_ROOT)
        assert p.exists()

    def test_keeps_other_checkouts_file(self, agents_dir, tmp_path):
        other = tmp_path / "elsewhere" / "checkout"
        p = _write_legacy(agents_dir, _generated_config(other))
        kiro_install.cleanup_legacy_composer_agent(agents_dir, REPO_ROOT)
        assert p.exists()

    def test_keeps_unparseable_file(self, agents_dir):
        p = agents_dir / "sdpm-composer.json"
        p.write_text("{not json", encoding="utf-8")
        kiro_install.cleanup_legacy_composer_agent(agents_dir, REPO_ROOT)
        assert p.exists()

    def test_noop_when_absent(self, agents_dir):
        kiro_install.cleanup_legacy_composer_agent(agents_dir, REPO_ROOT)  # no raise
        assert list(agents_dir.iterdir()) == []


class TestInstallerShape:
    def test_render_composer_agent_is_gone(self):
        assert not hasattr(kiro_install, "render_composer_agent")

    def test_template_file_is_gone(self):
        assert not (_INSTALL_PY.parent / "sdpm-composer.json.tmpl").exists()
