# SPDX-License-Identifier: MIT-0
"""Generate clone-free MCP client installation snippets from one config."""

from __future__ import annotations

import argparse
import base64
import json
import shlex
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "clients" / "uvx-config.json"
OUTPUT_PATH = ROOT / "clients" / "snippets.md"
CURSOR_BUTTON = "https://cursor.com/deeplink/mcp-install-dark.svg"


def load_config(path: Path = CONFIG_PATH) -> dict[str, Any]:
    """Load and minimally validate the canonical stdio server config."""
    config = json.loads(path.read_text(encoding="utf-8"))
    if set(config) != {"command", "args"}:
        raise ValueError("uvx config must contain exactly 'command' and 'args'")
    if not isinstance(config["command"], str) or not config["command"]:
        raise ValueError("uvx config command must be a non-empty string")
    if not isinstance(config["args"], list) or not all(isinstance(arg, str) for arg in config["args"]):
        raise ValueError("uvx config args must be an array of strings")
    return config


def compact_json(value: Any) -> str:
    """Serialize JSON deterministically for command lines and deep links."""
    return json.dumps(value, separators=(",", ":"), ensure_ascii=True)


def cursor_deep_link(config: dict[str, Any]) -> str:
    """Return Cursor's documented base64-encoded MCP install link."""
    encoded = base64.b64encode(compact_json(config).encode()).decode("ascii")
    return f"cursor://anysphere.cursor-deeplink/mcp/install?name=sdpm&config={encoded}"


def render_snippets(config: dict[str, Any]) -> str:
    """Render all client snippets that share the canonical uvx config."""
    link = cursor_deep_link(config)
    vscode_config = {"name": "sdpm", **config}
    kiro_args = compact_json(config["args"])
    claude_command = shlex.join(["claude", "mcp", "add", "sdpm", "--", config["command"], *config["args"]])
    generic_config = json.dumps({"mcpServers": {"sdpm": config}}, indent=2)

    return f"""<!-- AUTO-GENERATED by scripts/gen_client_snippets.py. DO NOT EDIT. -->

# MCP client installation snippets

All commands below are generated from `clients/uvx-config.json`.

## Cursor

[![Add to Cursor]({CURSOR_BUTTON})]({link})

Deep link: `{link}`

## Visual Studio Code

```sh
code --add-mcp {shlex.quote(compact_json(vscode_config))}
```

## Kiro CLI

```sh
kiro-cli mcp add --name sdpm --command {shlex.quote(config['command'])} --args {shlex.quote(kiro_args)} --scope global
```

## Claude Code

```sh
{claude_command}
```

## Generic MCP configuration

Use this `mcpServers` JSON for Claude Desktop manual configuration and other compatible clients:

```json
{generic_config}
```
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if clients/snippets.md is stale")
    args = parser.parse_args(argv)

    expected = render_snippets(load_config())
    if args.check:
        if not OUTPUT_PATH.is_file() or OUTPUT_PATH.read_text(encoding="utf-8") != expected:
            print(f"Generated client snippets are stale: run {Path(__file__).name}", file=sys.stderr)
            return 1
        print(f"OK: {OUTPUT_PATH.relative_to(ROOT)} is up to date")
        return 0

    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
